### ISSUE TITLE
Company annotations may contain newlines

### ISSUE THREAD

**Issue by jefftrull** [Sodel-the-Vociferous/helm-company#18]
I found that helm-company will often display a long list of `nil` in cases where `company-complete` will show completions. See image for an example. The code being completed is the same as [this comment](https://github.com/Sodel-the-Vociferous/helm-company/issues/7#issuecomment-495777634) but using clangd+LSP as the backend.
<img width="344" alt="company" src="https://user-images.githubusercontent.com/762705/62826798-03288400-bb77-11e9-8b95-9764f74bfd8d.png">
<img width="344" alt="helm" src="https://user-images.githubusercontent.com/762705/62826803-163b5400-bb77-11e9-957e-d7046cca8a63.png">

After lengthy investigation I have found what I believe to be the root cause: Company annotations may contain newlines. For example, `helm-company--get-annotations` returns the following for the third candidate:
```
" 
<iterator> (Class)"
```
i.e., `space`, `newline`, and then the rest of it. Since `helm-company` operates by inserting candidates into a buffer to be chosen one per line, we see more candidates than there really are, with the wrong names, and they cannot be found in the hashes we set up, resulting in the observed `nil`.

**Comment by Sodel-the-Vociferous** [comment]
Thank you for your troubleshooting, Jeff!

To start, I'll say that I definitely am open to fixing this in helm-company if it's necessary. However, I do have a few questions first.

- Can you please tell me which version of clangd (`clangd --version`) you are running?
- Can you please tell me what version of lsp-clangd you have installed? 
- Using your example, can you please show me the results of `M-x company-diag`? (I want to make sure that the backend you're using is definitely company-lsp.)

I'm asking because I tried duplicating this problem with company-lsp 20190612, lsp-clangd 20180828, clangd 7.0.1, and all emacs packages up to date on MELPA, and I'm not seeing the `nil` results you're seeing. I'm wondering if it was a bug that has been fixed upstream, because I don't think that it's correct behaviour for a backend to return annotation strings containing newlines. Though, again, I am open to fixing this behaviour here if necessary.

![Helm-Company Lsp+Clangd](https://user-images.githubusercontent.com/918813/62827014-64eaed00-bb7b-11e9-9b94-7b9ebb6bb1ef.png)

**Comment by jefftrull** [comment]
Update: adding `company--clean-string` to `helm-company--get-annotations` seems to fix it

**Comment by Sodel-the-Vociferous** [comment]
In that case, that looks like the right solution. I'll add it. Thanks!

**Comment by jefftrull** [comment]
clangd version 9.0.0 (trunk 364255)
[company-diag output](https://github.com/Sodel-the-Vociferous/helm-company/files/3489310/company_diag.txt)

And you are right, I'm not using lsp-clangd, that was deprecated :) That's been incorporated into lsp-mode itself, whose version is 20190810.1732.

I have a theory about why you don't see the nils - perhaps you and I use have different search settings? My company results only show prefix matches. Are there nils farther down in your results? I only have errors for templated functions and classes, which none of the candidates you show are.

**Comment by Sodel-the-Vociferous** [comment]
Heh, that does make sense.

Can you please test commit# 813eebf to make sure that it fixes your issue? If it does, I'll tag a new release.

**Comment by jefftrull** [comment]
I am unfortunately seeing the same issue as before :(

Are you able to reproduce the problem now?

**Comment by jefftrull** [comment]
Perhaps the issue is that the next usage (around line 244) lacks this fix

**Comment by Sodel-the-Vociferous** [comment]
Darn. :(

That's possible.

I haven't yet figured out how to reproduce it with the given example file.

**Comment by jefftrull** [comment]
Adding it to line 244 also fixes my issue.

**Comment by Sodel-the-Vociferous** [comment]
Give 21afdcb a try. I added it to `helm-company--get-annotations` instead of on the individual lines.

**Comment by jefftrull** [comment]
The new fix fails with the message `helm-company--clean-string: Wrong type argument: sequencep, 32
`

**Comment by Sodel-the-Vociferous** [comment]
I'm getting sloppy. I'll fix this properly in a few days when I'm not rushed.

**Comment by jefftrull** [comment]
No worries, thanks for looking at it so quickly!

**Comment by Sodel-the-Vociferous** [comment]
Give 74ff4d0 a try.

**Comment by jefftrull** [comment]
Sorry for the delay. Looks like you released it in the meantime? It's working now! Thanks a lot.

**Comment by Sodel-the-Vociferous** [comment]
I did indeed. Thank you so much for the digging you did into the root cause! That made it a pleasure to fix. Take care!
