### ISSUE TITLE
Autocomplete if there is only one candidate

### ISSUE THREAD

**Issue by dmalyuta** [Sodel-the-Vociferous/helm-company#20]
The current version of helm-company does not seem to robustly complete the candidate automatically, if there is only one candidate in the completion list. For me, sometimes it does and sometimes it doesn't do that. For example, suppose that I am trying to complete `MyFooBarClass`. When I type `MyFooB` and run helm-company, it sometimes shows a list with only one completion candidate (`MyFooBarClass`), instead of autocompleting it without showing the list. Could this possibly be improved to allow autocompletion, when there is only one candidate?

**Comment by Sodel-the-Vociferous** [comment]
Hi @dmalyuta.

This is an unfortunate limitation of how helm-company was developed. There is a "proper way" to develop frontends for company-mode, but helm-company doesn't follow those conventions. Unfortunately, that means that helm-company doesn't integrate wit company as easily as we would like.

Since this behaviour (autocompletion if there's only one candidate) is a behaviour in company-mode, not helm-company, I don't see a simple way to support this feature with helm-company's current code base. Sorry.

I will keep this in the back of my mind, in case I think of a way that I have time to implement. Thanks.

**Comment by Sodel-the-Vociferous** [comment]
Disregard my previous (deleted) comment about this being too hard. :D

The desired behaviour seems to be working consistently now. Thank you!
